# Generated by Django 3.0.8 on 2020-07-09 02:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200709_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='_blogger_subscribers_+', to='blog.Blogger'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 2, 44, 18, 729590, tzinfo=utc)),
        ),
    ]
