# Generated by Django 3.0.8 on 2020-07-09 02:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200709_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 2, 54, 16, 144788, tzinfo=utc)),
        ),
    ]
