# Generated by Django 3.0.8 on 2020-07-09 02:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200709_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 2, 55, 37, 288376, tzinfo=utc)),
        ),
    ]
