# Generated by Django 3.0.8 on 2020-07-09 11:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200709_0557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-rating']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish_datetime']},
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 11, 48, 47, 310715, tzinfo=utc)),
        ),
    ]
