# Generated by Django 3.0.8 on 2020-07-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200709_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
