# Generated by Django 3.0.8 on 2020-07-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200709_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_datetime',
            field=models.DateTimeField(),
        ),
    ]
